version: "2.1"

volumes:
  gearmand-data:
  gearman_webui-data:

services:
  gearmand:
    build:
      context: ./gearmand
#    network_mode: host
    image: gearmand-job-server
    container_name: gearmand
    hostname: gearmand
    ports:
      - 4730:4730
    volumes:
      - gearmand-data:/etc/gearman.conf
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.balena-socket: '1'
      io.balena.features.procfs: '1'
      io.balena.features.dbus: '1'
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
  gearman-webui:
    build:
      context: ./gearman-webui
    ports:
      - 80:80
    links:
      - gearmand:4730
    volumes:
      - gearman_webui-data:/gearmanui
    labels:
      io.balena.features.kernel-modules: '1'
